### ISSUE TITLE
Support auto save.

### ISSUE THREAD

**Issue by pragmatrix** [pragmatrix/BuildOnSave#23]
Even though SaveAllTheTime works quite well for me. It's probably worth a shot to integrate the autosave functionality into BuildOnSave, too.

**Comment by pragmatrix** [comment]
I've decided to try to start fixing related problems in SaveAllTheTime instead. Let's see how this progresses.

https://github.com/paulcbetts/SaveAllTheTime/pull/48

**Comment by abukres** [comment]
The issue I am having is that SaveAllTheTime sometimes doesn't save the same file it saved successfully earlier. It's not an all or nothing issue. I also do not know how to debug a VS extension while working in VS. If it's quick to learn, I can spend some time learning it.

**Comment by pragmatrix** [comment]
A good start would be to take a look into the log files after it failed to save a file and/or compile a debug version. On my machine, they are stored at `C:\Users\[username]\AppData\Roaming\SaveAllTheTime`. Also increasing the default debug level to `Trace` may help: https://github.com/paulcbetts/SaveAllTheTime/blob/master/SaveAllTheTime/NLog.dll.nlog

**Comment by pragmatrix** [comment]
Since I am working on a small web project, I've also experienced that problem and - hopefully - fixed another bug, that caused SATT to stop autosaving files: https://github.com/pragmatrix/SaveAllTheTime/releases/tag/1.4.0.3

**Comment by pragmatrix** [comment]
If there are further problems with SaveAllTheTime in combination with BuildOnSave, please report them to https://github.com/pragmatrix/SaveAllTheTime.
