### ISSUE TITLE
Add an option to build only the project that contains the file that has been saved.

### ISSUE THREAD

**Issue by pragmatrix** [pragmatrix/BuildOnSave#24]

**Comment by grieg** [comment]
my vote for this feature!

**Comment by pragmatrix** [comment]
Thank you @grieg! Could you elaborate about why and how you think this feature would improve your build scenario? I would really like to know more about how BuildOnSave is used and may be improved, and also suspect that this feature might lead to confusion, because - when enabled - it would never be clear what projects are actually up to date.

**Comment by grieg** [comment]
In my case, I have big solution with near hundred of projects, and rebuilding whole solution is slow. I may be working on some web project, that is on the end of hierarchy (no other projects reference this project, but this project depends on other) - in this scenario it would be useful to have this option  to rebuild on save only current project i am working on, to see results faster in browser.

**Comment by pragmatrix** [comment]
I'm trying to implement a BuildType mode "Projects Of Saved Files" (name may change), that builds all the projects that have recent changed / saved files, but ignores all the dependent projects for now. It's a bit more complicated than I thought, because multiple projects may need to be built in one go. If this works, it could help solve #14 in case multiple startup projects are configured.

@grieg I wonder why the solution build is so slow when files are changed in projects that are not referred by other projects. Also, have you tried using the "Startup Project" mode, or are you changing files of different projects all the time?

**Comment by pragmatrix** [comment]
I've made a new release with the additional build mode "Build Projects of Saved Files". https://github.com/pragmatrix/BuildOnSave/releases/tag/0.19

@grieg If you do have some spare time, could you try installing this release and take a look if that is what you need to make your turnarounds faster?

**Comment by grieg** [comment]
Hello @pragmatrix! I've tried release 0.19 in  "Build Projects of Saved Files" mode, but it fails to build anything - i got the following error: 
```
---------- BuildOnSave: Project: Web.Admin, Configuration: Debug Any CPU ----------
C:\Git\csharp\Cian.sln.metaproj : error MSB4057: The target "Web_Admin" does not exist in the project.
Done building project "Cian.sln" -- FAILED.
========== BuildOnSave: 0 succeeded, 0 failed ==========
```
Also if I use "Build of startup Project" I got the same error. If I use Build menu in Visual Studio it builds ok, so I don't think that it is problem with my project.

**Comment by pragmatrix** [comment]
Hello @grieg, I just found out that this happens when the project that should be built is not enabled for the solution build in the solution's configuration. Can you confirm that?

In the example below, when I build `Web.Site` with BuildOnSave, the same error happens. If the project is selected for build, BuildOnSave works as expected.

![image](https://cloud.githubusercontent.com/assets/1003751/14642795/1aba445c-064c-11e6-8b76-e1b009a9fa4f.png)
