### ISSUE TITLE
BuildOnSave CRASHED

### ISSUE THREAD

**Issue by eggersa** [pragmatrix/BuildOnSave#52]
Unfortunately I am unable to tell what exactly caused this issue. I do however quiet often get the following output from BuildOnSave using Visual Studio 2017:

> ---------- BuildOnSave CRASHED, please report to https://www.github.com/pragmatrix/BuildOnSave/issues
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at BuildOnSave.Projects.DependentProjectKeys(BuildDependencies dependencies, Project project)
>    at BuildOnSave.Projects.DependentMap(BuildDependencies dependencies, Project[] all)
>    at BuildOnSave.Projects.AffectedProjects(BuildDependencies dependencies, Project[] all, Project[] roots)
>    at BuildOnSave.BackgroundBuild2.tryMakeBuildRequest(String startupProject_, String[] changedProjectPaths)
>    at BuildOnSave.Driver.beginBuild(String startupProject_, String[] changedProjects)
>    at BuildOnSave.Driver.beginBuild(Solution solution, BuildType buildType, IEnumerable`1 projects)
>    at BuildOnSave.Driver.beginBuild()

**Comment by picrap** [comment]
Same thing for me.

**Comment by picrap** [comment]
I've updated to 0.30 and unfortunately the problem still appears (in the form of a MessageBox, now). Let me know if you need help (such as logs, running other debug version, etc.).

**Comment by pragmatrix** [comment]
> (in the form of a MessageBox, now)

Great, thanks, I need a screenshot, there should be a line numbers listed in there.

**Comment by picrap** [comment]
Here it is!

![assertion failed abort quit retry debug ignore continue](https://user-images.githubusercontent.com/251429/47900540-8f39ac80-de7d-11e8-8254-e5aff9eef9cb.png)

**Comment by pragmatrix** [comment]
https://github.com/pragmatrix/BuildOnSave/releases/tag/0.31 should fix that problem. If it does not, please  reopen this issue. Thanks.
