### ISSUE TITLE
Cannot install on VS2019 Preview 4.4

### ISSUE THREAD

**Issue by hnen** [pragmatrix/BuildOnSave#56]
Attempting to install on VS2019 Preview 4.4. Tried installing from VS Extension Manager (Extensions -> Manage Extensions). Extension manager shows version 0.32 for BuildOnSave extension. After restarting VS2019, installation fails with following error: `This extension cannot be installed because the following references are missing: Microsoft.VisualStudio.Component.CoreEditor`

![build_on_save_err](https://user-images.githubusercontent.com/853546/55210829-f7ed4100-51f1-11e9-930d-8b7d53d9e860.PNG)

**Comment by pragmatrix** [comment]
Hi, thank you for the reporting that.

I've built a new pre-release, which should install just fine: 
https://github.com/pragmatrix/BuildOnSave/releases/tag/0.34.
