### ISSUE TITLE
Can't install in Visual Studio 2019 release version. Missing prerequisites?

### ISSUE THREAD

**Issue by abukres** [pragmatrix/BuildOnSave#58]
I am unable to install it in VS 2019 release. I downloaded the vsix file from the market place and I get the message below when I try to install it. What prerequisites am I missing?

This extension cannot be installed to this product due to prerequisites that cannot be resolved

**Comment by pragmatrix** [comment]
Hi, thank you for reporting this. Please try to install the pre-release 0.34 from here: https://github.com/pragmatrix/BuildOnSave/releases/tag/0.34 and I would appreciate if you report back if the extension works as expected.

If I get enough positive feedback, I will release this version to the market place.

**Comment by KacperSzczypior** [comment]
I don't know how it worked for @abukres, but the pre-release version allowed installing BuildOnSave on my machine at least. It's probably worth noting that I had a different error during installation, the message was about Microsoft.VisualStudio.Component.CoreEditor missing.

After of pre-release version everything seems to be working correctly

**Comment by pragmatrix** [comment]
I've tested the extension a today with Visual Studio 2019 and it seems to work fine, meaning that I will close this issue and release version 0.34 to the market place.
